import pytest
from pathlib import Path

from asdl.emit.backend_config import (
    BackendConfig,
    DEFAULT_PATTERN_RENDERING,
    SystemDeviceTemplate,
    REQUIRED_SYSTEM_DEVICES,
    load_backend_config,
    validate_system_devices,
)
from asdl.diagnostics import Severity

BACKEND_NAME = "sim.ngspice"
EXAMPLES_BACKENDS = (
    Path(__file__).resolve().parents[3] / "examples" / "config" / "backends.yaml"
)


def test_load_valid_backend_config(tmp_path: Path) -> None:
    """Test loading a valid backend config."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text(
        """
sim.ngspice:
  extension: ".spice"
  comment_prefix: "*"
  templates:
    __subckt_header__: ".subckt {name} {ports}"
    __subckt_header_params__: ".subckt {name} {ports} {params}"
    __subckt_footer__: ".ends {name}"
    __subckt_call__: "X{name} {ports} {ref}"
    __subckt_call_params__: "X{name} {ports} {ref} {params}"
    __netlist_header__: "* Generated by ASDL"
    __netlist_footer__: ".end"
"""
    )

    config = load_backend_config(BACKEND_NAME, config_file)
    assert config.name == BACKEND_NAME
    assert config.extension == ".spice"
    assert config.comment_prefix == "*"
    assert len(config.templates) == 7
    assert config.pattern_rendering == DEFAULT_PATTERN_RENDERING
    assert config.templates["__subckt_header__"].template == ".subckt {name} {ports}"
    assert (
        config.templates["__subckt_header_params__"].template
        == ".subckt {name} {ports} {params}"
    )
    assert config.templates["__subckt_footer__"].template == ".ends {name}"
    assert config.templates["__subckt_call__"].template == "X{name} {ports} {ref}"
    assert (
        config.templates["__subckt_call_params__"].template
        == "X{name} {ports} {ref} {params}"
    )
    assert config.templates["__netlist_header__"].template == "* Generated by ASDL"
    assert config.templates["__netlist_footer__"].template == ".end"


def test_load_missing_backend(tmp_path: Path) -> None:
    """Test loading a backend that doesn't exist in config."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text(
        """
sim.ngspice:
  extension: ".spice"
  comment_prefix: "*"
  templates: {}
"""
    )

    with pytest.raises(KeyError, match="spectre"):
        load_backend_config("sim.spectre", config_file)


def test_load_missing_file() -> None:
    """Test loading from a non-existent config file."""
    with pytest.raises(FileNotFoundError):
        load_backend_config(BACKEND_NAME, Path("/nonexistent/backends.yaml"))


def test_load_pattern_rendering_policy(tmp_path: Path) -> None:
    """Test parsing pattern rendering policy from backend config."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text(
        """
sim.ngspice:
  extension: ".spice"
  comment_prefix: "*"
  pattern_rendering: "[{N}]"
  templates:
    __subckt_header__: ".subckt {name} {ports}"
    __subckt_header_params__: ".subckt {name} {ports} {params}"
    __subckt_footer__: ".ends {name}"
    __subckt_call__: "X{name} {ports} {ref}"
    __subckt_call_params__: "X{name} {ports} {ref} {params}"
    __netlist_header__: "* Generated by ASDL"
    __netlist_footer__: ".end"
"""
    )

    config = load_backend_config(BACKEND_NAME, config_file)
    assert config.pattern_rendering == "[{N}]"


def test_validate_missing_required_devices() -> None:
    """Test validation fails when required system devices are missing."""
    config = BackendConfig(
        name=BACKEND_NAME,
        extension=".spice",
        comment_prefix="*",
        templates={
            "__subckt_header__": SystemDeviceTemplate(template=".subckt {name}"),
        },
    )

    diags = validate_system_devices(config)
    assert len(diags) > 0
    assert any(d.severity == Severity.ERROR for d in diags)
    for device in REQUIRED_SYSTEM_DEVICES:
        if device == "__subckt_header__":
            continue
        assert any(device in d.message for d in diags)


def test_validate_missing_parameterized_required_devices() -> None:
    """Test validation reports missing parameterized subckt system templates."""
    config = BackendConfig(
        name=BACKEND_NAME,
        extension=".spice",
        comment_prefix="*",
        templates={
            "__subckt_header__": SystemDeviceTemplate(template=".subckt {name}"),
            "__subckt_footer__": SystemDeviceTemplate(template=".ends {name}"),
            "__subckt_call__": SystemDeviceTemplate(
                template="X{name} {ports} {ref}"
            ),
            "__netlist_header__": SystemDeviceTemplate(template="* Generated by ASDL"),
            "__netlist_footer__": SystemDeviceTemplate(template=".end"),
        },
    )

    diags = validate_system_devices(config)
    assert len(diags) == 1
    assert diags[0].severity == Severity.ERROR
    assert "__subckt_header_params__" in diags[0].message
    assert "__subckt_call_params__" in diags[0].message


def test_validate_all_required_devices_present() -> None:
    """Test validation passes when all required devices are present."""
    config = BackendConfig(
        name=BACKEND_NAME,
        extension=".spice",
        comment_prefix="*",
        templates={
            "__subckt_header__": SystemDeviceTemplate(template=".subckt {name}"),
            "__subckt_header_params__": SystemDeviceTemplate(
                template=".subckt {name} {params}"
            ),
            "__subckt_footer__": SystemDeviceTemplate(template=".ends {name}"),
            "__subckt_call__": SystemDeviceTemplate(
                template="X{name} {ports} {ref}"
            ),
            "__subckt_call_params__": SystemDeviceTemplate(
                template="X{name} {ports} {ref} {params}"
            ),
            "__netlist_header__": SystemDeviceTemplate(template="* Generated by ASDL"),
            "__netlist_footer__": SystemDeviceTemplate(template=".end"),
        },
    )

    diags = validate_system_devices(config)
    assert len(diags) == 0


@pytest.mark.parametrize(
    ("backend_name", "expected_header_fragment", "expected_call_fragment"),
    [
        ("sim.ngspice", ".subckt {name} {ports} {params}", "X{name} {ports} {ref} {params}"),
        ("sim.xyce", ".subckt {name} {ports} PARAMS: {params}", "X{name} {ports} {ref} PARAMS: {params}"),
        (
            "sim.spectre",
            "subckt {name} ({ports}) parameters {params}",
            "{name} ({ports}) {ref} parameters {params}",
        ),
    ],
)
def test_examples_backends_include_parameterized_subckt_templates(
    backend_name: str,
    expected_header_fragment: str,
    expected_call_fragment: str,
) -> None:
    """Assert golden backend config keeps simulator-owned parameterized syntax."""
    config = load_backend_config(backend_name, EXAMPLES_BACKENDS)
    assert expected_header_fragment in config.templates["__subckt_header_params__"].template
    assert expected_call_fragment in config.templates["__subckt_call_params__"].template


def test_load_with_empty_templates(tmp_path: Path) -> None:
    """Test loading backend config with empty templates."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text(
        """
sim.ngspice:
  extension: ".spice"
  comment_prefix: "*"
  templates:
    __subckt_header__: ".subckt {name} {ports}"
    __subckt_header_params__: ".subckt {name} {ports} {params}"
    __subckt_footer__: ".ends {name}"
    __subckt_call__: "X{name} {ports} {ref}"
    __subckt_call_params__: "X{name} {ports} {ref} {params}"
    __netlist_header__: ""
    __netlist_footer__: ""
"""
    )

    config = load_backend_config(BACKEND_NAME, config_file)
    assert config.templates["__netlist_header__"].template == ""
    assert config.templates["__netlist_footer__"].template == ""

    diags = validate_system_devices(config)
    assert len(diags) == 0
