import pytest
from pathlib import Path

from asdl.emit.backend_config import (
    BackendConfig,
    SystemDeviceTemplate,
    REQUIRED_SYSTEM_DEVICES,
    load_backend_config,
    validate_system_devices,
)
from asdl.diagnostics import Severity


def test_load_valid_backend_config(tmp_path: Path) -> None:
    """Test loading a valid backend config."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text("""
ngspice:
  system_devices:
    __subckt_header__:
      template: ".subckt {name} {ports}"
    __subckt_footer__:
      template: ".ends {name}"
    __subckt_call__:
      template: "X{name} {ports} {ref}"
    __netlist_header__:
      template: "* Generated by ASDL"
    __netlist_footer__:
      template: ".end"
""")

    config = load_backend_config("ngspice", config_file)
    assert config.name == "ngspice"
    assert len(config.system_devices) == 5
    assert config.system_devices["__subckt_header__"].template == ".subckt {name} {ports}"
    assert config.system_devices["__subckt_footer__"].template == ".ends {name}"
    assert config.system_devices["__subckt_call__"].template == "X{name} {ports} {ref}"
    assert config.system_devices["__netlist_header__"].template == "* Generated by ASDL"
    assert config.system_devices["__netlist_footer__"].template == ".end"


def test_load_missing_backend(tmp_path: Path) -> None:
    """Test loading a backend that doesn't exist in config."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text("ngspice:\n  system_devices: {}\n")

    with pytest.raises(KeyError, match="spectre"):
        load_backend_config("spectre", config_file)


def test_load_missing_file() -> None:
    """Test loading from a non-existent config file."""
    with pytest.raises(FileNotFoundError):
        load_backend_config("ngspice", Path("/nonexistent/backends.yaml"))


def test_validate_missing_required_devices() -> None:
    """Test validation fails when required system devices are missing."""
    config = BackendConfig(
        name="ngspice",
        system_devices={
            "__subckt_header__": SystemDeviceTemplate(template=".subckt {name}"),
            # Missing other required devices
        },
    )

    diags = validate_system_devices(config)
    assert len(diags) > 0
    assert any(d.severity == Severity.ERROR for d in diags)
    assert any("__subckt_footer__" in d.message for d in diags)
    assert any("__subckt_call__" in d.message for d in diags)
    assert any("__netlist_header__" in d.message for d in diags)
    assert any("__netlist_footer__" in d.message for d in diags)


def test_validate_all_required_devices_present() -> None:
    """Test validation passes when all required devices are present."""
    config = BackendConfig(
        name="ngspice",
        system_devices={
            "__subckt_header__": SystemDeviceTemplate(template=".subckt {name}"),
            "__subckt_footer__": SystemDeviceTemplate(template=".ends {name}"),
            "__subckt_call__": SystemDeviceTemplate(template="X{name} {ports} {ref}"),
            "__netlist_header__": SystemDeviceTemplate(template="* Generated by ASDL"),
            "__netlist_footer__": SystemDeviceTemplate(template=".end"),
        },
    )

    diags = validate_system_devices(config)
    assert len(diags) == 0


def test_load_with_empty_templates(tmp_path: Path) -> None:
    """Test loading backend config with empty templates."""
    config_file = tmp_path / "backends.yaml"
    config_file.write_text("""
ngspice:
  system_devices:
    __subckt_header__:
      template: ".subckt {name} {ports}"
    __subckt_footer__:
      template: ".ends {name}"
    __subckt_call__:
      template: "X{name} {ports} {ref}"
    __netlist_header__:
      template: ""
    __netlist_footer__:
      template: ""
""")

    config = load_backend_config("ngspice", config_file)
    assert config.system_devices["__netlist_header__"].template == ""
    assert config.system_devices["__netlist_footer__"].template == ""

    # Validation should still pass with empty templates
    diags = validate_system_devices(config)
    assert len(diags) == 0
