"""PatternedGraph core dataclasses and registries."""

from .graph import (
    EndpointBundle,
    InstanceBundle,
    InstId,
    ModuleGraph,
    ModuleId,
    NetBundle,
    NetId,
    ProgramGraph,
)
from .registries import (
    AnnotationIndex,
    AxisId,
    AxisSpec,
    ExprId,
    GraphId,
    GroupSlice,
    ParamPatternOriginIndex,
    PatternExpr,
    PatternExpressionRegistry,
    PatternOriginIndex,
    PatternSegment,
    RegistrySet,
    SchematicHints,
    SourceSpanIndex,
)

__all__ = [
    "AnnotationIndex",
    "AxisId",
    "AxisSpec",
    "EndpointBundle",
    "ExprId",
    "GraphId",
    "GroupSlice",
    "InstanceBundle",
    "InstId",
    "ModuleGraph",
    "ModuleId",
    "NetBundle",
    "NetId",
    "ParamPatternOriginIndex",
    "PatternExpr",
    "PatternExpressionRegistry",
    "PatternOriginIndex",
    "PatternSegment",
    "ProgramGraph",
    "RegistrySet",
    "SchematicHints",
    "SourceSpanIndex",
]
