"""PatternedGraph and AtomizedGraph core dataclasses and registries."""

from .atomized_graph import (
    AtomizedEndpoint,
    AtomizedEndpointId,
    AtomizedInstance,
    AtomizedInstId,
    AtomizedModuleGraph,
    AtomizedModuleId,
    AtomizedNet,
    AtomizedNetId,
    AtomizedProgramGraph,
    PatternedEndpointId,
    PatternedInstId,
    PatternedModuleId,
    PatternedNetId,
)
from .dump import dump_patterned_graph, patterned_graph_to_jsonable
from .graph_builder import PatternedGraphBuilder
from .graph import (
    EndpointBundle,
    InstanceBundle,
    InstId,
    ModuleGraph,
    ModuleId,
    NetBundle,
    NetId,
    ProgramGraph,
)
from .index import GraphIndex
from .query import DesignQuery, query
from .pipeline import run_patterned_graph_pipeline
from .registries import (
    AnnotationIndex,
    AxisId,
    AxisSpec,
    ExprId,
    GraphId,
    GroupSlice,
    ParamPatternOriginIndex,
    PatternExpr,
    PatternExpressionRegistry,
    PatternOriginIndex,
    PatternSegment,
    RegistrySet,
    SchematicHints,
    SourceSpanIndex,
)

__all__ = [
    "AtomizedEndpoint",
    "AtomizedEndpointId",
    "AtomizedInstance",
    "AtomizedInstId",
    "AtomizedModuleGraph",
    "AtomizedModuleId",
    "AtomizedNet",
    "AtomizedNetId",
    "AtomizedProgramGraph",
    "AnnotationIndex",
    "AxisId",
    "AxisSpec",
    "DesignQuery",
    "dump_patterned_graph",
    "EndpointBundle",
    "ExprId",
    "GraphId",
    "GroupSlice",
    "GraphIndex",
    "InstanceBundle",
    "InstId",
    "ModuleGraph",
    "ModuleId",
    "NetBundle",
    "NetId",
    "ParamPatternOriginIndex",
    "PatternExpr",
    "PatternExpressionRegistry",
    "PatternOriginIndex",
    "PatternSegment",
    "PatternedGraphBuilder",
    "patterned_graph_to_jsonable",
    "PatternedEndpointId",
    "PatternedInstId",
    "PatternedModuleId",
    "PatternedNetId",
    "ProgramGraph",
    "query",
    "RegistrySet",
    "run_patterned_graph_pipeline",
    "SchematicHints",
    "SourceSpanIndex",
]
